name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para a branch que você usa

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'  # Altere para a versão do Ruby que você usa

      - name: Install dependencies
        run: |
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --destination ./build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
